[package]
name = "gradle_modules_graph"
version = "0.1.0"
authors = ["Andrey <bolduzev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
