[package]
name = "gradle_modules_graph"
version = "0.1.0"
authors = ["Andrey <bolduzev@gmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3.0"
itertools = "0.9.0"
regex = "1.3.9"
lazy_static = "1.4.0"
rand = "0.7.3"
